# Generated by Django 4.1.3 on 2023-01-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_comment_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter_email',
            field=models.EmailField(max_length=20),
        ),
    ]
