# Generated by Django 4.1.3 on 2023-01-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_comment_commenter_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
