# Generated by Django 4.1.3 on 2023-02-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strategy',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
