# Generated by Django 4.1.3 on 2023-02-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_strategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='strategy',
            new_name='featured',
        ),
    ]
