# Generated by Django 4.1.3 on 2023-01-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_product_brand_alter_product_description'),
        ('users', '0005_alter_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default=False, max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=255)),
                ('total_price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('product', models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
