# Generated by Django 4.1.3 on 2023-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(help_text='0=Nam, 1=Nữ', max_length=20, null=True),
        ),
    ]
