# Generated by Django 4.1.3 on 2023-01-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='unknow@gmail.com', max_length=20)),
                ('address', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(help_text='0=Nam, 1=Nữ', max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('position', models.CharField(max_length=255)),
                ('salary', models.IntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
