# Generated by Django 4.1.3 on 2023-01-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('d', 'Delivered'), ('c', 'Cancelled'), ('f', 'Finished')], default='p', max_length=1),
        ),
    ]
